"""add_table_dashboard_role_to_core_dashboard_model.py

Revision ID: f1630a1380dd
Revises: 55e910a74826
Create Date: 2018-11-14 08:05:20.050048

"""

# revision identifiers, used by Alembic.
revision = 'f1630a1380dd'
down_revision = '55e910a74826'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('dashboard_role')
    # ### end Alembic commands ###
